# Generated by Django 4.2.20 on 2025-03-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0002_burger_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burger',
            options={'verbose_name': 'Burger', 'verbose_name_plural': 'Burgers'},
        ),
        migrations.AlterField(
            model_name='burger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='image',
            field=models.ImageField(blank=True, upload_to='burgers/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='burger',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
    ]
